### PR TITLE
hdlc_util: Merge findings of TC2219001

### PR DESCRIPTION
**Pull request by ckloecker**

### CODE REVIEW

**Comment by mad-jrodriguez** [comment]
conflicts already fixed

**Comment by dpfeuffer** [comment]
This open pull request shall be handled for the upcoming 13MD05-90_02_05 release.
I'm wondering of the direction of this merge:
image
Testing should be done with the mad-dev branch.

**Comment by dpfeuffer** [comment]
@DHofbauer 
I added you as reviewer for this merge request because (according CSR) the testing is actually running at your desk, but I'm not sure witch version are you testing.
Can you give us an approval of the functional changes of this merge request?

**Comment by mad-jrodriguez** [comment]
> This open pull request shall be handled for the upcoming 13MD05-90_02_05 release. I'm wondering of the direction of this merge: image Testing should be done with the mad-dev branch.

Hi Dieter,

Yesterday I had to resolve a conflict in the merge so for this reason the "merge" arrow goes in the other direction. I used the github editor to resolve the conflict. Once this pull request is merged, the line will point to the other direction.

**Comment by dpfeuffer** [comment]
Ok, thanks for your explanation, I saw it just now. ;-)

**Review by mad-jrodriguez — APPROVED** [review]

**Pull request merged**
